server:
  port: 8100
spring:
  redis:
    host: 192.168.76.100
    port: 6379
    database: 0
    timeout: 1800000
    password: hzk123456
  cloud:
#    nacos:
#      discovery:
#        server-addr: 139.198.127.41:8848
#        namespace: ada979f6-9477-4867-be38-2a5ce4142346
    gateway:
      discovery:      #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator:      #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
          enabled: true
      routes:
        - id: service-acl
          uri: lb://service-acl
          predicates:
            - Path=/*/acl/**
        - id: service-base
          uri: lb://service-base
          predicates:
            - Path=/*/base/**
        - id: service-inbound
          uri: lb://service-inbound
          predicates:
            - Path=/*/inbound/**
        - id: service-outbound
          uri: lb://service-outbound
          predicates:
            - Path=/*/outbound/**
        - id: service-inventory
          uri: lb://service-inventory
          predicates:
            - Path=/*/inventory/**

